### ISSUE TITLE
Frequent Console Errors

### ISSUE THREAD

**Issue by Armandeus66** [therealguy90/foundrytodiscord#40]
**Describe the bug**
Errors in console.
```
foundrytodiscord | Attempting POST request...
main.js:109 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'actor')
    at getCondition (main.js:109:35)
    at Object.fn (main.js:48:33)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13604:13)
    at foundry.js:13576:43
    at Array.map (<anonymous>)
    at #handleCreateDocuments (foundry.js:13576:33)
```
and
```
Foundrytodiscord | Attempting POST request...
commons.js:2070 Error: You are accessing the ChatMessagePF2e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:2059:19)
    at ChatMessagePF2e._logV10CompatibilityWarning (commons.js:8544:14)
    at get data (commons.js:8432:24)
    at Object.fn (tabbed-chatlog.js:178:25)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at ChatMessagePF2e.getHTML (foundry.js:20720:11)
    at async ChatMessagePF2e.chatMessageGetHTML (chatMessage.ts:15:19)
    at async ChatMessagePF2e.getHTML (pf2e.mjs:1358:31620)
    at async ChatLogPF2e.postOne (foundry.js:85744:18)
logCompatibilityWarning @ commons.js:2070
workflow.js:180 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'actor')
    at workflow.conditionEscape (workflow.js:180:23)
    at workflow.go (workflow.js:98:15)
    at Object.fn (index.js:162:27)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13604:13)
    at foundry.js:13576:43
    at Array.map (<anonymous>)
    at #handleCreateDocuments (foundry.js:13576:33)
```
**To Reproduce**
1. Information is written to chat during an encounter.

**Expected behavior**
No errors.

**Additional context**
PF2E 5.15.3
Foundry 11.315

**Comment by therealguy90** [comment]
This doesn't look like an error from this module... method getCondition isn't from this module. Provide with more details:

- Does the module work with all other modules deactivated?
- ChatMessage object where this error occurred (preferably include ChatMessage.content)

**Comment by therealguy90** [comment]
In fact, this might be related to a PR in Tabbed Chatlog:

https://github.com/cswendrowski/FoundryVTT-Tabbed-Chatlog/pull/76

**Comment by therealguy90** [comment]
Closing due to lack of activity.
